### ISSUE TITLE
[BUG] finder extension ,auto off after turn on

### ISSUE THREAD

**Issue by qbmiller** [alienator88/Pearcleaner#232]
### Describe the bug:
finder extension ,auto off after turn on 

### Steps to reproduce:

![Image](https://github.com/user-attachments/assets/11ffe534-b91f-4b91-9fcb-3e8b94bdf391)

1. turn on 
2. it will turn off auto ,don't h=know why 
3. on application ,right click no uninstall with pearclanner

**Comment by alienator88** [comment]
If you open Debug window with CMD+D and try to turn it on again, does it record any errors?

**Comment by future-generation** [comment]
i have the same issue. no records in debug console if i try to turn switch on.
after i changed config section and go back, the switch immediately goes to the off position

**Comment by alienator88** [comment]
FYI, I can reproduce this as well. I'm on macOS 15.4.
I haven't touched the code to enable/disable the finder extension in a while. I'm guessing the latest versions of macOS might've altered something.
I'll look into it and see what I can find.

**Comment by alienator88** [comment]
I think I found out what the issue is, working on a fix now

**Comment by alienator88** [comment]
Yeah, fixed.
Will have this out in the next release.

**Comment by alienator88** [comment]
v4.4.1 with fix released.

**Comment by lum7671** [comment]
I updated to v4.4.1, but the issue is still not resolved.
Please check again.

Thank you always :-)


<img width="912" alt="Image" src="https://github.com/user-attachments/assets/1047c5f1-5a43-478a-ac4e-1b6b89987bec" />

<img width="827" alt="Image" src="https://github.com/user-attachments/assets/5d873178-bc4f-408e-b1c5-9ee4197e2ee7" />

```shell
➜  ~ brew reinstall --cask pearcleaner
Found existing alias for "brew reinstall --cask". You should use: "bcrin"
==> Downloading https://github.com/alienator88/Pearcleaner/releases/download/4.4.1/Pearcleaner.zip
Already downloaded: /Users/x/Library/Caches/Homebrew/downloads/781c186f52d7184ff717a709fa8dc3c795e0f7c01822794130ff0979fd1b18ec--Pearcleaner.zip
==> Uninstalling Cask pearcleaner
==> Removing launchctl service com.alienator88.PearcleanerSentinel
==> Backing App 'Pearcleaner.app' up to '/usr/local/Caskroom/pearcleaner/4.4.1/Pearcleaner.app'
==> Removing App '/Applications/Pearcleaner.app'
==> Purging files for version 4.4.1 of Cask pearcleaner
==> Installing Cask pearcleaner
==> Moving App 'Pearcleaner.app' to '/Applications/Pearcleaner.app'
🍺  pearcleaner was successfully installed!
➜  ~
```

**Comment by alienator88** [comment]
Hmm..so I just tested the extension on the following:
1. Physical mac running 15.4
2. VM running 15.4
3. VM running 15.3.2
4. Admin and standard user accounts

They all show the extension in Settings and can enable/use it without problems.
I'm really not sure why you're seeing an issue still.

I was able to reproduce your problem before I added the new fix in to 4.4.1, but I can't see it anymore.
What mac device are you running from?
And I'm assuming you're an admin user on this computer?

**Comment by alienator88** [comment]
@qbmiller @future-generation do you all see an issue with the extension in the newest release as well?

**Comment by alienator88** [comment]
Oh that's a good catch. They likely have some managed profiles installed to prevent certain extensions.
I'm on a company laptop too with MDM software but I'm not getting extensions blocked luckily 😅
