### ISSUE TITLE
[BUG] After deleting an app, there some app label left on the screen

### ISSUE THREAD

**Issue by AuthorProxy** [alienator88/Pearcleaner#337]
<img width="883" height="493" alt="Image" src="https://github.com/user-attachments/assets/873b024e-ed35-43c6-89e3-a4fa9ad2310f" />

<img width="1501" height="608" alt="Image" src="https://github.com/user-attachments/assets/bedd838f-e05e-4b2c-9508-621c8131550a" />

this is an old bug, it was existing on all versions I used

**Comment by alienator88** [comment]
How can I reproduce? I haven't seen it myself yet. 
Are you just dropping an app on top of Pearcleaner? Or multi selecting apps to uninstall multiple? 
If you have steps for me to reach that bug, I'd appreciate it!

**Comment by AuthorProxy** [comment]
1. Choose an app from a list
2. Delete
3. ... [first screen]
4. Select any other app [second screen]

It is not always reproducible. Now, after restarting the app, it disappeared, but I am sure it will happen again later. The next time I encounter it, I will record a video for you.

**Comment by alienator88** [comment]
There's gotta be a race condition or something there.
The only time that screen should show where it says "Sentinel Monitor.." is when there are no files left to remove but the application that was on screen is not cleared away from memory. 
When clicking the Trash button to remove files for an app, at the very end of the function it clears the app info from memory and should send you back to the main dashboard screen and hide all that stuff you're seeing.

**Comment by AuthorProxy** [comment]
Sometimes it doesn't send back until restart, like on the screen, and this floating label keeps floating )

**Comment by alienator88** [comment]
Try the new release, I think I fixed it.

**Comment by AuthorProxy** [comment]
ok close I will reopen with video if it repeats, I will test later

**Comment by alienator88** [comment]
Sounds good. I'll keep an eye out.

**Comment by AuthorProxy** [comment]
1. Selected an App "Motrix".
2. Click delete (homebrew started deleting)
3. Close homebrew console cross button after it finished.
4. Result...

- Motrix dissappeared from the app`s list.
- Motrix files list - still here (see screenshot)
- /Users/authorproxy/Library/Preferences/app.motrix.native.plist - not deleted
- it shows trash from trashbin

There are several issues. Files (like plists) are not deleted completely, but the app has already disappeared from the list. This means I can't select it again to delete the leftover files from the first attempt. If this is the intended behavior, the app's file list view should close forcefully, and any undeleted files should be moved to an "orphaned files" section. Ideally, these files should be deleted correctly on the first run, or don't remove the app from the list if there some files that couldn't be deleted at the moment. So you cannot left trash in the system because of some errors during uninstallation/deletion

@alienator88 is this intended behaviour?

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/fa23ed6e-1ae1-4623-935d-7bada2597a30" />

**Comment by alienator88** [comment]
@AuthorProxy can I ask how the app is selected or how it's being opened?
Looking at your screenshot, I see Motrix in the queue list:
<img width="251" height="190" alt="Image" src="https://github.com/user-attachments/assets/3ce37993-cf70-4712-9660-b0abaec822f3" />

That normally only happens in 2 scenarios:
1. If multi-select is enabled in the app list and you check the box next to Motrix
2. If you open Motrix in Pearcleaner externally either by drag/drop, Finder extension, etc.

I need to reproduce the issue exactly how you are and seeing the queue list at the bottom tells me that maybe it wasn't just clicked like normal in the apps list maybe?

Does the issue happen when that queue list is not there either during regular operation?

**Comment by alienator88** [comment]
I tried to reproduce your issue on v5.0.9 and the latest test build I'm working on right now and I can't get that issue to happen:

https://github.com/user-attachments/assets/f05f8b2c-1102-4ef9-8cd0-4176699059bb

It has to be related to that queue thing being at the bottom in your screenshot, maybe when the queue is displayed something is happening. But I'll need your exact repro steps to fix it.

**Comment by AuthorProxy** [comment]
So the steps exactly the same I described, I selected app from a list, using search box to filter list first. I am not sure that the bug is reproducible, I will try today later to reproduce it

**Comment by alienator88** [comment]
So the steps you mention should not show the app name in the queue list here:

<img width="251" height="190" alt="Image" src="https://github.com/user-attachments/assets/ac94c361-4fc8-497e-94bb-8e844a3a7ef0" />

I'm not sure how you are getting the app name in there if all you're doing is searching for the app and selecting it.
The ONLY time an app should be added to that queue list along the bottom is when opened externally via drag/drop, Finder extension, deeplinks, etc.

**Comment by AuthorProxy** [comment]
@alienator88 not sure is it the same bug that was before, but result looks similar

https://www.veed.io/view/42555c67-0b1c-4566-bc34-ccc2a1edb9df?panel=share&source=%2Ftools%2Fvideo-hosting%2Fvideo-upload

PS: how did you upload video to an issue? I have an error each time I am trying to do it.

**Comment by alienator88** [comment]
What version of the app are you on? That looks older, I don't have the sidebar on the left side anymore.
And I'm fairly sure I fixed this issue already in the latest version.

Github has a size limit of like 10mb or something. My videos are short and small is probably why.

**Comment by alienator88** [comment]
This should be resolved in the latest version (5.2.1) so I'll close this out. Feel free to reply back if it isn't and we can keep looking at it.

**Comment by AuthorProxy** [comment]
@alienator88 it is not resolved, latest version. Selected app (installed via homebrew), Changed sensivity to less aggressive, removed app. Result:

<img width="1389" height="651" alt="Image" src="https://github.com/user-attachments/assets/69e1c593-c71d-4f6e-b3a9-93779070ca16" />

**Comment by alienator88** [comment]
I'll need a recording of you doing the following, I can't reproduce on my side:
1. Start recording
2. Open Pearcleaner and show the settings window for a second on the interface tab so I can confirm some settings
3. Reproduce your issue
4. Send me recording

**Comment by AuthorProxy** [comment]
@alienator88 https://disk.yandex.ru/i/JrwHglRubjYcvg

and one settings group missed on the video 

<img width="795" height="758" alt="Image" src="https://github.com/user-attachments/assets/431573ac-038a-4d8f-b46c-95f39e5e137b" />

This is type of behaviour is happened when I have appcleaner that detects that something putted in the trash and started smartcleaner, after that pearcleaner smartcleaner detects that something deleted and started it's own smartdelete - thats why it is zero files and just a label on the bottom. I think this is the most easiest to reproduce or fix

**Comment by alienator88** [comment]
I see, that makes sense if you're using 2 cleaners at the same time with the sentinel monitor enabled.
The new version I'm working on should be capturing all the same stuff AppCleaner is, I made the search algorithm a lot more robust. So hopefully soon you won't see the AppCleaner popup very much anymore 😂

**Comment by AuthorProxy** [comment]
@alienator88 you can also add the condition that if there nothing to delete - go to the initial screen instead of showing empty page with a label/s, if I deleted manually it for example - before the search finished. or if homebrew cleanup deleted all files, or any other condition. I am not sure that appcleaner is the only way to produce this bug.

**Comment by alienator88** [comment]
Have you seen another way to repro this, yours is the first time I've seen this specific issue?

Not sure it makes sense to make the view auto-switch to home screen if there's no files found.
Say a user opens Pearcleaner and loads the app list.
Then they remove an app and all it's files outside of Pearcleaner.
That app is still cached in the list if you don't CMD+R to refresh it. You click on the app and it will tell you there's no files found or something along those lines.
If I make it auto-switch to home page, it doesn't make much sense to the user. They clicked on an app and then it just puts them back on the page where they just clicked an app from with no UI notification on why that happened.

Unless we can find another way to reproduce this where more users would encounter it, I don't think I'll be putting time into this specific issue right now.
