### ISSUE TITLE
[BUG] `pear list-orphaned` doesn't work

### ISSUE THREAD

**Issue by Xarius86** [alienator88/Pearcleaner#472]
### New Issue Checklist

- [x] I updated Pearcleaner to the latest version and still observe the issue
- [x] I searched for [existing GitHub issues](https://github.com/alienator88/pearcleaner/issues)
- [x] OS Version: 26.1
- [x] Pearcleaner Version: 5.4.2

---

### Issue:
`pear list-orphaned` just hangs and produces no output. It must be killed with `CTRL` + `C`.

**Comment by alienator88** [comment]
This is fixed in my local build now. Will have it out in next release.

**Comment by tim-korso** [comment]
Still reproduces on **5.4.3** (the release that was supposed to contain the fix) — **macOS 26.3.1** (build 25D771280a), `searchSensitivity=1`.

## Reproduction

- `Pearcleaner list-orphaned` hangs indefinitely at ~0% CPU, never produces output
- `gtimeout 150 /Applications/Pearcleaner.app/Contents/MacOS/Pearcleaner list-orphaned` → **exit 124, 0 bytes of output** (reproduced 3×, both raw CLI and via a wrapper)
- Main process sits at ~67MB RSS doing nothing; `PearcleanerHelper` spawns but accumulates ~0.05s of CPU then goes idle
- Other CLI paths work fine: `Pearcleaner list /Applications/Espanso.app` returns results in ~2.8s; argument parsing responds instantly

The orphan scan appears to wait on the XPC helper that never does any work when the app isn't running in the foreground. Reopening since the shipped 5.4.3 still exhibits the original hang. Happy to run any diagnostic or attach sysdiagnose output.
